### ISSUE TITLE
Create Fake Data

### ISSUE THREAD

**Issue by hugaskardo** [hugaskardo/cabinproject#1]
Need fake data to test the model : 
2 Cabins 
Attrs : 
- Number of rooms
- Number of bathrooms
-Number of beads
- Number of leaving rooms
- kitchen amenities 
- Number of persons that can stay

**Comment by javierrv** [comment]
It was installed ember-cli-mirage to create fake data.
It was created a Fixture called cabin where the data is loaded.
It was created a a Route in mirage to /cabins.
It was created a Model called cabin to hold the data.
