### ISSUE TITLE
Add Newest Bootstrap Library using bower or some shit like that

### ISSUE THREAD

**Issue by hugaskardo** [hugaskardo/cabinproject#3]
Add bootstrap and set a basic menu bar on the application template, that display home page and cabins page (routes)

**Comment by javierrv** [comment]
it was added using bower, bower install bootstrap --save

**Comment by javierrv** [comment]
The dependency keeps save in the bower_components folder but it must be imported in the project using app.import('path'); in the ember-cli-builds.js file

**Comment by hugaskardo** [comment]
I CANTsee the BASIC MENU BAR ON THE APPLICATION TEMPLATE

**Comment by javierrv** [comment]
It was made a basic navbar, still needs to be specified the elements that it'll contain
