### ISSUE TITLE
Add the chile routs to the project.

### ISSUE THREAD

**Issue by hugaskardo** [hugaskardo/cabinproject#4]
Add the child routes to the cabins eg : localhost:1111/cabin/laArcaica you should use the id otherwise ember will not work, im telling by experience . so it should be call on the parameters something like route cabin/cabin_id

**Comment by javierrv** [comment]
The routes added are cabins and cabin
/cabins    shows all cabins available
/cabin/1
/cabin/2 show a cabin that was selected from the previous list

**Comment by javierrv** [comment]
The routes are working with numbers, later they will be working with the cabin's names
