### ISSUE TITLE
Add the landing page

### ISSUE THREAD

**Issue by hugaskardo** [hugaskardo/cabinproject#5]
Chose the best way to set a Landing page, for now we just need a Blank page that display a bootstrap button an set it to go to home page, that should display the Cabins info, in future this landing page will display images and videos of the cabins.

**Comment by javierrv** [comment]
It was made a route for home
/home
another for landing
/landing
the previous routes cabins and cabin are accessible through
/home/cabins
/home/cabin/1
/home/cabin/2

**Comment by javierrv** [comment]
The routes were kept exactly the same, the landing page will be made later
